#!/usr/bin/env python3
"""Generates the Kotlin and Swift book tables from data/. Run after editing anything in data/."""
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
books = json.loads((root / "data/books.json").read_text())
languages = [json.loads(p.read_text()) for p in sorted((root / "data/languages").glob("*.json"))]

KOTLIN_OUT = root / "android/src/main/kotlin/com/kevinissac/verserefkit/BookData.kt"
SWIFT_OUT = root / "Sources/VerseRefKit/BookData.swift"
HEADER = "Generated by tools/generate.py from data/ — do not edit by hand."


def q(s):
    return json.dumps(s, ensure_ascii=False)


def kotlin():
    out = [f"// {HEADER}", "package com.kevinissac.verserefkit", "", "internal object BookData {", ""]
    out.append("    val canonicalBooks: List<Pair<String, String>> = listOf(")
    out += [f"        {q(b['code'])} to {q(b['name'])}," for b in books["books"]]
    out += ["    )", "", "    val englishAliases: List<Pair<String, String>> = listOf("]
    out += [f"        {q(a)} to {q(b['code'])}," for b in books["books"] for a in b["aliases"]]
    out += ["    )", "", "    val codeAliases: Map<String, String> = mapOf("]
    out += [f"        {q(a)} to {q(c)}," for a, c in books["codeAliases"].items()]
    out += ["    )", "", "    val chapterVerseCounts: Map<String, List<Int>> = mapOf("]
    out += [f"        {q(b['code'])} to listOf({', '.join(map(str, b['verses']))})," for b in books["books"]]
    out += ["    )", "", "    // One entry per language: USFM code -> names and abbreviations.",
            "    val languageNames: List<Map<String, List<String>>> = listOf("]
    for lang in languages:
        out.append("        mapOf(")
        out += [f"            {q(c)} to listOf({', '.join(map(q, n))})," for c, n in lang["names"].items()]
        out.append("        ),")
    out += ["    )", "}", ""]
    KOTLIN_OUT.parent.mkdir(parents=True, exist_ok=True)
    KOTLIN_OUT.write_text("\n".join(out))


def swift():
    out = [f"// {HEADER}", "", "enum BookData {", ""]
    out.append("    static let canonicalBooks: [(code: String, name: String)] = [")
    out += [f"        ({q(b['code'])}, {q(b['name'])})," for b in books["books"]]
    out += ["    ]", "", "    static let englishAliases: [(alias: String, code: String)] = ["]
    out += [f"        ({q(a)}, {q(b['code'])})," for b in books["books"] for a in b["aliases"]]
    out += ["    ]", "", "    static let codeAliases: [String: String] = ["]
    out += [f"        {q(a)}: {q(c)}," for a, c in books["codeAliases"].items()]
    out += ["    ]", "", "    static let chapterVerseCounts: [String: [Int]] = ["]
    out += [f"        {q(b['code'])}: [{', '.join(map(str, b['verses']))}]," for b in books["books"]]
    out += ["    ]", "", "    /// One entry per language: USFM code -> names and abbreviations.",
            "    static let languageNames: [[String: [String]]] = ["]
    for lang in languages:
        out.append("        [")
        out += [f"            {q(c)}: [{', '.join(map(q, n))}]," for c, n in lang["names"].items()]
        out.append("        ],")
    out += ["    ]", "}", ""]
    SWIFT_OUT.parent.mkdir(parents=True, exist_ok=True)
    SWIFT_OUT.write_text("\n".join(out))


kotlin()
swift()
